image: freebsd/latest
packages:
  - rubygem-jekyll
  - lftp
sources:
  - https://git.sr.ht/~pwr/paulwrankin.com
environment:
  JEKYLL_ENV: production
  HOST: https://myfiles.fastmail.com
  REMOTE_PATH: /paulwrankin.com/www
secrets:
  - 663f93d3-0e8f-4bd7-915a-6294b321128a
triggers:
  - action: email
    condition: always
    to: Paul W. Rankin <hello@paulwrankin.com>
tasks:
  - build: |
      cd paulwrankin.com
      jekyll build
  - deploy: |
      cd paulwrankin.com
      lftp -c "open --user pwr@fastmail.com ${HOST}; mirror --reverse --only-newer --delete _site ${REMOTE_PATH}"
