# Site settings
title: "Paul W. Rankin"
description: >-
  Paul W. Rankin is a filmmaker based in Brisbane, Australia.
url: http://www.paulwrankin.com
base_url: /
ga_id: UA-61824324-1

# Build settings
assets: /assets/
permalink: /:title/
future: true
excerpt_separator: "<!-- more -->"
collections:
  pages:
    output: true
    permalink: /:path/
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

# Data
email: "&#104;&#101;&#108;&#108;&#111;&#64;&#112;&#97;&#117;&#108;&#119;&#114;&#97;&#110;&#107;&#105;&#110;&#46;&#99;&#111;&#109;"
nav:
  - name: "filmmaking"
    url: /filmmaking/
  - name: "writing"
    url: /writing/
  - name: "code"
    url: /code/
  - name: "contact"
    url: /contact/
  - name: "etc"
    url: /etc/

keyboard_shortcuts:
  - key: "g h"
    url: /
  - key: "g f"
    url: /filmmaking/
  - key: "g w"
    url: /writing/
  - key: "g c"
    url: /code/
  - key: "g e"
    url: /etc/
  - key: "g n"
    url: /now/
  - key: "g ~"
    url: http://files.paulwrankin.com/
  - key: "?"
    url: /keyboard/

# Formats
date_format: "%-d %B %Y"
