title: "Paul W. Rankin"
url: "https://www.paulwrankin.com"
base_url: "/"
email: "&#104;&#101;&#108;&#108;&#111;&#64;&#112;&#97;&#117;&#108;&#119;&#114;&#97;&#110;&#107;&#105;&#110;&#46;&#99;&#111;&#109;"
description: >-
  Paul W. Rankin is a filmmaker based in Brisbane, Australia.
timezone: Australia/Brisbane
repository: rnkn/paulwrankin.com
permalink: "blog/:year/:title/"
date_format: "%-d %B %Y"
permalink_date_format: "%F at %-I:%M %P"
future: true
assets: "/images/"
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME

collections:
  sections:
    output: true
    permalink: "/:path/"
  projects:
    output: true
    permalink: "/:title/"

defaults:
  - scope:
      type: posts
    values:
      layout: post
  - scope:
      type: projects
    values:
      layout: project
