# Site settings
title: "Paul W. Rankin"
description: >-
  Paul W. Rankin is a filmmaker based in Brisbane, Australia.
base_url: /
repository: rnkn/paulwrankin.com

# Build settings
timezone: Australia/Brisbane
assets: /assets/
permalink: /:title/
future: true
gems:
- jekyll-redirect-from
whitelist:
- jekyll-redirect-from
exclude:
- Gemfile
- Gemfile.lock
- README.md

# Data
email: "&#104;&#101;&#108;&#108;&#111;&#64;&#112;&#97;&#117;&#108;&#119;&#114;&#97;&#110;&#107;&#105;&#110;&#46;&#99;&#111;&#109;"
nav:
- url: /
  key: "g h"
- name: "directing"
  url: /directing/
- name: "editing"
  url: /editing/
- name: "screenwriting"
  url: /screenwriting/
- name: "live&nbsp;visuals"
  url: /live/
- name: "fiction"
  url: /fiction/
- name: "code"
  url: /code/
- name: "contact"
  url: /contact/
- key: "g ~"
  url: http://files.paulwrankin.com/
- key: "?"
  url: /keyboard/
rates:
- role: director
  day: 800
  week: 3200
- role: editor
  day: 400
  week: 1600

# Formats
date_format: "%-d %B %Y"
excerpt_separator: "<!-- more -->"
