# Site settings
title: "Paul W. Rankin"
description: >-
  Paul W. Rankin is a filmmaker based in Brisbane, Australia.
base_url: /
repository: rnkn/paulwrankin.com

# Build settings
assets: /assets/
permalink: /:title/
future: true
gems:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

# Data
email: "&#104;&#101;&#108;&#108;&#111;&#64;&#112;&#97;&#117;&#108;&#119;&#114;&#97;&#110;&#107;&#105;&#110;&#46;&#99;&#111;&#109;"
nav:
  - url: /
    key: "g h"
  - name: "filmmaking"
    url: /filmmaking/
    key: "g f"
  # - name: "writing"
  #   url: /writing/
  #   key: "g w"
  - name: "code"
    url: /code/
    key: "g c"
  - name: "info"
    url: /info/
    key: "g i"
  - key: "g ~"
    url: http://files.paulwrankin.com/
  - key: "?"
    url: /keyboard/
hero: "_posts/2016-11-09-lumber.md"

# Formats
date_format: "%-d %B %Y"
excerpt_separator: "<!-- more -->"
