title: "Paul W. Rankin"
url: "https://www.paulwrankin.com"
email: "&#104;&#101;&#108;&#108;&#111;&#64;&#112;&#97;&#117;&#108;&#119;&#114;&#97;&#110;&#107;&#105;&#110;&#46;&#99;&#111;&#109;"
description: >-
  Paul W. Rankin is a filmmaker based in Brisbane, Australia.
timezone: Australia/Brisbane
repository: "rnkn/paulwrankin.com"
github_username: "rnkn"
date_format: "%-d %B %Y"
future: true
assets: "/assets/"
include:
  - _redirects
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME

collections:
  posts:
    output: true
    permalink: "/:title/"
  sections:
    output: true
    permalink: "/:path/"
